{{- $password := .Values.mongodb.password | default (randAlphaNum 16) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.instance.clusterName | quote }}
type: Opaque
stringData:
  password: {{ $password | quote }}
  username: {{ .Values.mongodb.instance.username | quote }}